SAN-135 Change terminology to penalty reference instead of reference number
companieshouse/penalty-payment-web pull request #188
Opened 2024-12-20 15:01 UTC by klai-ch

SAN-135 change terminology to penalty reference instead of reference number

2024-12-20 15:36 UTC, dgordon-ch approved these changes

2024-12-23 10:49 UTC, acallaghan-ch requested changes

2025-01-02 09:57 UTC, ch-code-analysis commented
CI: Security warnings found!

2025-01-02 10:15 UTC, ch-code-analysis commented
CI: Security warnings found!

2025-01-02 13:00 UTC, klai-ch commented on src/main/java/uk/gov/companieshouse/web/pps/util/PenaltyUtils.java
>      public String getReferenceTitle(final String penaltyNumber) {
Updated from the suggestion

2025-01-02 13:09 UTC, ch-code-analysis commented
CI: Security warnings found!

2025-01-02 14:54 UTC, rbull-ch commented on src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
> +        model.addAttribute("referenceTitle", penaltyUtils.getReferenceTitle());
I'd say that this model attribute and utility method should now be removed entirely and simply update the template instead (templates/pps/viewPenalties.html)?

We can specify a message property here to populate the text instead to make it easier in the future e.g. `th:text="#{viewPenalties.penalty-ref-title}"`

See [details.penalty-ref-label.LATE_FILING](https://github.com/search?q=repo%3Acompanieshouse%2Fpenalty-payment-web%20details.penalty-ref-label.LATE_FILING&type=code)

2025-01-02 15:29 UTC, klai-ch commented on src/main/java/uk/gov/companieshouse/web/pps/controller/pps/ViewPenaltiesController.java
> +        model.addAttribute("referenceTitle", penaltyUtils.getReferenceTitle());
Updated and moved to message property file for the title

2025-01-02 15:34 UTC, ch-code-analysis commented
CI: Security warnings found!

2025-01-02 16:47 UTC, rbull-ch approved these changes

2025-01-03 09:49 UTC, acallaghan-ch approved these changes

2025-01-03 10:04 UTC, merged